language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y g++-4.7 libgtest-dev google-mock
  - cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib
  - cd -
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz -O glog.tar.gz
  - tar -xzf glog.tar.gz
  - cd glog*
  - ./configure && make && sudo make install
  - cd -
before_script:
  - ./bootstrap.sh
script:
  - CXX=g++-4.7 ./configure && make && make check
