language: cpp
compiler:
  - gcc
env:
  - CXX_VERSION=4.8
  - CXX_VERSION=4.7
before_install:
# g++ 4.7 or 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# google-glog
  - sudo add-apt-repository -y ppa:fcitx-team/nightly
  - sudo apt-get update
  - sudo apt-get install -y g++-${CXX_VERSION} libboost1.48-dev libboost-filesystem1.48-dev libboost-system1.48-dev libgoogle-glog-dev autoconf-archive
  - export CXX="g++-${CXX_VERSION}"
  - sudo pip install cpp-coveralls --use-mirrors
  - cd test
  - wget http://googlemock.googlecode.com/files/gmock-1.7.0.zip && unzip gmock-*.zip
  - cd gmock-1.7.0
  - ./configure && make
  - cd ../..
before_script:
  - ./bootstrap
script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - CFLAGS='-g -O0' CXXFLAGS='-g -O0' ./configure --enable-gcov && make && make check
after_success:
  - cp vobla/.libs/libvobla_la-*.gc* vobla
  - if [[ $CXX == 'g++-4.7' ]]; then coveralls --gcov gcov-4.7 -e test -e vobla/.libs; fi
notifications:
  email:
    - xulei82@gmail.com
    - zil.huang@gmail.com
