language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y g++-4.7 libboost1.48-dev
  - sudo pip install git+git://github.com/eddyxu/cpp-coveralls.git#egg=cpp_coveralls --use-mirrors
  - cd test
  - wget https://googletest.googlecode.com/files/gtest-1.6.0.zip && unzip gtest-*.zip
  - cd gtest-1.6.0
  - CXX=g++-4.7 ./configure && make
  - cd ../..
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz -O glog.tar.gz
  - tar -xzf glog.tar.gz
  - cd glog*
  - ./configure && make && sudo make install
  - cd -
before_script:
  - ./bootstrap
script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - CXX=g++-4.7 ./configure --enable-gcov && make && make check
after_success:
  - coveralls --gcov gcov-4.7 -e test -e glog-0.3.3
notifications:
  email:
    - xulei82@gmail.com
    - zil.huang@gmail.com
