language: cpp
compiler:
  - gcc
env:
  - CXX_VERSION=4.8
  - CXX_VERSION=4.7
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y g++-${CXX_VERSION}
  - export CXX="g++-${CXX_VERSION}"
  - sudo pip install cpp-coveralls --use-mirrors
  - cd test
  - wget http://googlemock.googlecode.com/files/gmock-1.6.0.zip && unzip gmock-*.zip
  - cd gmock-1.6.0
  - ./configure && make
  - cd ../..
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz -O glog.tar.gz
  - tar -xzf glog.tar.gz
  - cd glog*
  - ./configure && make && sudo make install
  - cd -
before_script:
  - ./bootstrap
script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - CFLAGS='-g -O0' CXXFLAGS='-g -O0' ./configure --enable-gcov && make && make check
after_success:
  - cp vobla/.libs/libvobla_la-*.gc* vobla
  - if [[ $CXX == 'g++-4.7' ]]; then coveralls --gcov gcov-4.7 -e test -e glog-0.3.3 -e vobla/.libs; fi
notifications:
  email:
    - xulei82@gmail.com
    - zil.huang@gmail.com
