#!/bin/sh -
#
# Re-generate ./configure and Makefile.in files.
#
# Copyright 2013 (c) Lei Xu <eddyxu@gmail.com>

if [ -d .git/hooks ]; then
	# vobla is used as an individual project.
	cp contrib/pre-commit .git/hooks
fi

case `uname` in
	Darwin*) glibtoolize --copy ;;  # For MacOSX
    *) libtoolize --copy ;; # Otherwise.
esac

autoheader
if [ -d /usr/local/share/aclocal ]; then
	aclocal -I m4 -I /usr/local/share/aclocal --install
else
	aclocal -I m4 --install
fi
autoconf

automake --foreign --add-missing --force-missing --copy
